sonar.projectKey=santhoshv98_project
sonar.organization=santhoshv98

sonar.sources=src
sonar.tests=src/test
sonar.exclusions=src/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
